export const ADD_TO_CART="ADD_TO_CART";
export const SET_TOTAL_COUNT="SET_TOTAL_COUNT";
export const SET_TOTAL_SIZE="SET_TOTAL_SIZE";
export const SET_EMPTY_CART="SET_EMPTY_CART";
export const REMOVE_CART_ITEM="REMOVE_CART_ITEM";
export const MINUS_ITEM="MINUS_ITEM";
export const PLUS_ITEM="PLUS_ITEM";
export const SET_TYPE_FROM_LOCALSTORAGE="SET_ITEM_FROM_LOCALSTORAGE"
